services:
  
  postgres:
    container_name: maino_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: maino_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - maino_network
  
  redis:
    image: redis
    container_name: maino_redis
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DATABASES: 1
    volumes:
      - redis_data:/data
    networks:
      - maino_network
  
  web:
    depends_on:
      - postgres
      - redis
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    networks:
      - maino_network
    volumes:
     - .:/app-rails 
  
  nginx:
    image: nginx
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: maino_nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - maino_network


  sidekiq:
    build: .
    container_name: sidekiq_maino
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    networks:
      - maino_network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 81:80
    networks:
      - maino_network


volumes:
  postgres_data:
  redis_data:

networks:
  maino_network:
    driver: bridge