default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: postgres



development:
  <<: *default
  database: maino_development


test:
  <<: *default
  database: maino_test

production:
  primary: &primary_production
    <<: *default
    database: maino
  cache:
    <<: *primary_production
    database: blog_maino_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: blog_maino_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: blog_maino_production_cable
    migrations_paths: db/cable_migrate
